pipeline{
  agent any

  environment{
      Release = '20.04'
  }

  stages{
    stage('build'){
      environment{
        LOG_LEVEL='INFO'
      }
      steps{
        echo "Building release ${Release} with log level ${LOG_LEVEL}..."
      }
    }
    stage('Test'){
      steps{
        echo "Testing release ${Release}"
        writeFile file:'test-results.txt', text:'passed'

      }
    }
  }
  post{
    success{
        archiveArtifacts 'test-results.txt'
    }
  }
}
