pipeline{
  agent any

  environment{
      Release = '20.04'
  }

  stages{
    stage('build'){
      agent any
      environment{
        LOG_LEVEL='INFO'
      }
      steps{
        echo "Building release ${Release} with log level ${LOG_LEVEL}..."
      }
    }
    stage('Test'){
      steps{
        echo "Testing release ${Release}"
      }
    }
    stage('Deploy'){
        input {
            message 'Deploy?'
            ok 'Do it!'
            parameters{
                string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
            }
        }
        steps{
            echo "Deploying release ${Release} to environment ${TARGET_ENVIRONMENT}"
        }
    }

  }
  post{
    always{
        echo "Prints whether deploy happened or not, success or failure"
    }
  }
}
