pipeline{
  agent any
  environment{
      Release = '20.04'
  }
  stages{
    stage('build'){
      environment{
        LOG_LEVEL='INFO'
      }
      steps{
        echo "Building release ${Release} with log level ${LOG_LEVEL}..."
        sh 'chmod +x m2/demo3/build.sh'
        withCredentials([string(credentialId: 'an-api-key', variable: 'API_KEY')])
        sh '''
            ./m2/demo3/build.sh
           '''
      }
    }
    stage('Test'){
      steps{
        echo "Testing release ${Release}"
        writeFile file:'test-results.txt', text:'passed'
      }
    }
  }
  post{
    success{
        archiveArtifacts 'test-results.txt'
    }
  }
}
